### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by alberto-riggi** [scale-tone/DurableFunctionsMonitor#1]
Hi,
I cloned the repo, I tried to run the npm installation and I got an integrity check error on the lodash package.

npm WARN tarball tarball data for lodash@4.17.13 (sha512-cQKh8igo5QUhZ7lg38DYWAxMvjSAKG0A8wGSVimP07SIUEK2UO+arSRKbRZWtelMtN5V0Hkwh5ryOto/SshYIg==) seems to be corrupted. which make everything fail.
Seems like that was the sha of version 4.17.11. I tried the one used here
https://github.com/microsoft/accessibility-insights-service/pull/202/files
and it worked properly.
 integrity sha512-vm3/XWXfWtRua0FkUyEHBZy8kCPjErNBT9fJx8Zvs+U6zjqPbTUOpkaoum3O5uiA8sm+yNMHXfYkTUHFoMxFNA==

**Comment by scale-tone** [comment]
Thanks, Alberto, for fixing this!
