### ISSUE TITLE
Suggestion: Add Task event IDs to the instance history view

### ISSUE THREAD

**Issue by cgillum** [scale-tone/DurableFunctionsMonitor#108]
When viewing task history in DFM, it would be useful to distinguish multiple copies of the same activity function (or sub-orchestration) with its task event ID. This would also allow users to correlate activity executions to specific events in the [Durable Task Framework logs](https://docs.microsoft.com/azure/azure-functions/durable/durable-functions-diagnostics#durable-task-framework-logging).

For example, here is the current instance details display (using docker.io/scaletone/durablefunctionsmonitor:4.6):

![image](https://user-images.githubusercontent.com/2704139/125710458-e7848987-2e5f-4961-a2a3-8d3af2514701.png)

In my example above, I call the "CountWords" activity 5 times in parallel. However, I don't have a way to distinguish them from each other except for their return values.  If you look at the history table in storage, you'll see that we actually have this information available:

![image](https://user-images.githubusercontent.com/2704139/125710878-9a5f3d3a-ef27-4d80-a20e-29b7a485656c.png)

So combining this information, it would be great to add it in the UI, something like this:

![image](https://user-images.githubusercontent.com/2704139/125711260-f9d62cc8-a47e-4fec-a1af-6abc9a984964.png)

These task event IDs are monotonically increasing, so it's also possible to correlate them back to specific `CallActivityAsync` calls in the code.

**Comment by scale-tone** [comment]
Sounds interesting, but did I get you correctly that the ultimate goal of retrieving these TaskScheduleIds would be to allow navigating to particular activity _invocations_ in the code? Or can you think of other possible use cases?

In my mind, a link to an activity invocation would in 99% of cases just point to the same code line (potentially in a loop body, as in your case) - activities are rarely called twice or trice, aren't they? More useful would be to quickly jump to an activity _definition_  - and that already works in VsCode ext (need to have the relevant project opened):
![image](https://user-images.githubusercontent.com/5447190/125803919-c73bb798-3984-4f9c-b666-45ce109a802c.png)

**Comment by cgillum** [comment]
I wasn’t thinking of these as clickable links (I shouldn’t have made them blue). I just wanted to display the number. Users can correlate the number to code or logs manually if that happens to be useful to them.

**Comment by scale-tone** [comment]
Then I guess, it's a matter of adding an extra `TaskScheduleId` field to this list. 
But in that case it now makes much more sense to grab the history directly from table, bypassing DurableOrchestrationStatus.History field. Which, as of today, doesn't return enough fields and plus doesn't support paging.
Will try to keep DurableOrchestrationStatus.History as a fallback...

**Comment by scale-tone** [comment]
Implemented in v4.7. Pls, validate.
