### ISSUE TITLE
All rendered JSON is capped at 1024 characters

### ISSUE THREAD

**Issue by thegrahamking** [scale-tone/DurableFunctionsMonitor#109]
All rendered JSON is capped at 1024 characters.  Otherwise `[${result.length} symbols long JSON]` is displayed.

This is particularly a problem when an activity of a certain function fails and results in an exception.  The `Result` and `Details` are not visible when monitoring the status of the orchestration instance.

It should be possible to view full activity exception details.

**Comment by scale-tone** [comment]
Thanks @thegrahamking . I assume that you're referring to the Execution History on the Orchestration Details page, correct?
Would it help, if that lengthy JSON could be opened and viewed in a popup window?

**Comment by thegrahamking** [comment]
Yep, [this](https://raw.githubusercontent.com/scale-tone/DurableFunctionsMonitor/master/readme/screenshots/orchestration-details.png) page specifically but anywhere it's currently capped being able to view in a popup would be great.

**Comment by scale-tone** [comment]
Fixed in v4.7. Pls, validate.

**Comment by thegrahamking** [comment]
@scale-tone 4.7 isn't available on docker hub, any ideas why not?

**Comment by scale-tone** [comment]
Yes, it was my mistake, I messed up with its release pipeline and accidentally pushed v4.7 image with '4.6' tag.
Just pushed the [correct tag as well](https://hub.docker.com/layers/scaletone/durablefunctionsmonitor/4.7/images/sha256-3752e9b9d7da990fb205727ad36e05095b9ae1958e6f29b1f55e4022b7d61ac2?context=explore).

Thanks for noticing!
