### ISSUE TITLE
Running `AzureStorageEmulator.exe clear all` crash the backend permanently

### ISSUE THREAD

**Issue by MaximRouiller** [scale-tone/DurableFunctionsMonitor#110]
Running this extension locally and running `AzureStorageEmulator.exe clear all` fails the backend permanently. There are no options to "restart" the backend short of closing vscode.

I feel like having a VSCode extension command that would allow us to restart the backend could end up providing a workaround to a lot of issues people are facing. If the restart could ask us to provide the URL again, it would allow us to swap between "localhost" and "Azure" as well.

**Comment by scale-tone** [comment]
Hi @MaximRouiller , 

These buttons:
![image](https://user-images.githubusercontent.com/5447190/126226787-39c6b1fb-9218-4df7-8a63-0f604d202500.png)
![image](https://user-images.githubusercontent.com/5447190/126227059-ee5423b8-c5b8-4bf7-9d73-c1a527072aff.png)

are intended for the purpose of restarting a (potentially failed) backend. Don't they work in your scenario?


> If the restart could ask us to provide the URL again, it would allow us to swap between "localhost" and "Azure" as well.

This I'm not completely following, to be honest. Would you like to be able to point VsCode ext to a DfMon backend, that runs in Azure?
If yes, then it would require substantial efforts to secure this communication channel, while benefits of this aren't clear to me. After all, each running backend is equipped with the same UI, which you can always point your browser to...
Can you elaborate on when this feature could be useful?

Also, today it's technically possible to modify the backend's URL to be used:
![image](https://user-images.githubusercontent.com/5447190/126227926-44b0c1ec-819c-4041-8424-e957b6569c72.png)

And it would even work with your *Azure-hosted* backend, if you disable auth on it (which I suggest you don't do).

**Comment by scale-tone** [comment]
Let's hope that resolved it.
If not, please, create another bug.
