### ISSUE TITLE
Broken Gantt chart for 4.7.0

### ISSUE THREAD

**Issue by MaximRouiller** [scale-tone/DurableFunctionsMonitor#112]
Different version of the extension, same function visualization.

4.6 screenshot:
![Gantt on 4.6](https://user-images.githubusercontent.com/209384/127907790-c12b786b-3635-433b-96c5-4c44f621ba70.png)

4.7 screenshot:
![Gantt on 4.7](https://user-images.githubusercontent.com/209384/127907826-4bb0a1f4-1099-4af0-a27d-ce83e4247bb0.png)

**Comment by scale-tone** [comment]
Hmm,that's weird. Can you please also include both screenshots of the 'Details' tab (or at least event histories)?

**Comment by scale-tone** [comment]
Fixed with v4.7.1
