### ISSUE TITLE
[Proposal] Support multiple storage connections and multiple hubs in VsCode ext

### ISSUE THREAD

**Issue by scale-tone** [scale-tone/DurableFunctionsMonitor#12]
Right now, if you want to connect to another hub and/or a different storage account with the VsCode extension, you need to restart VsCode.

The proposal is to let the user connect to multiple different storage accounts/hubs and visualize  currently established connections (storage accounts->hubs) in form of a [Tree View](https://code.visualstudio.com/api/extension-guides/tree-view). That will also allow to view/manage the list of existing hubs created in each storage account and to show some quick statistics around them.

**Comment by scale-tone** [comment]
Support for multiple Task Hub connections added in [v3.0](https://github.com/scale-tone/DurableFunctionsMonitor/releases/tag/v3.0). 

Further enhancements should include populating the list of Task Hubs automatically, persisting the list (but not the connection info!) and finally to allow managing (deleting) the Task Hubs themselves.

**Comment by scale-tone** [comment]
With (v3.1)[https://github.com/scale-tone/DurableFunctionsMonitor/releases/tag/v3.1] VsCode extension is now showing you the list of existing Task Hubs in your Storage Account. This is how you can see how many of them you already have there.
Last step is to implement removal of unused ones...

**Comment by scale-tone** [comment]
Implemented 'Delete Task Hub...' context menu item in VsCode extension v3.2

**Comment by Arithmomaniac** [comment]
> persisting the list (but not the connection info!)

Definitely would love this feature. Also, why not the connection info too?

**Comment by scale-tone** [comment]
Thanks for your feedback, @Arithmomaniac , promoted this to a separate ticket: #30 .
