### ISSUE TITLE
Start new instance from Functions Graph does not work on VS Code

### ISSUE THREAD

**Issue by pregoli** [scale-tone/DurableFunctionsMonitor#124]
![image](https://user-images.githubusercontent.com/7696950/131260749-91ed0a43-d731-4b33-8f22-e8e2a91141b2.png)

I tried to use the "Start new instance" feature from the Functions Graph section multiple times, both for new and exsisting project.
The result is always as shown in the above screenshot.

Any thoughts?

**Comment by scale-tone** [comment]
@pregoli , I suspect, your Task Hub is called 'TestHubName' (the default name when running locally). Is that correct? :)

**Comment by pregoli** [comment]
Yes, @scale-tone , why? It doesn't work with the default taskHub running on storage emulator?
Thanks

**Comment by scale-tone** [comment]
> Yes

Then I'm afraid, we're bound with [this issue](https://github.com/Azure/azure-functions-durable-extension/issues/1926) (basically, DurableClient treats this name as special and disallows external starts/restarts to it).
But if you just [choose a different Task Hub name](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-task-hubs?tabs=csharp#task-hub-names), then it should work fine.

**Comment by pregoli** [comment]
Thanks @scale-tone !

**Comment by scale-tone** [comment]
Found a workaround, published an updated VsCode ext (v4.8.1).  In v4.8.1 all task hub names should work now.
