### ISSUE TITLE
changing time range loses selected sorting

### ISSUE THREAD

**Issue by drdamour** [scale-tone/DurableFunctionsMonitor#126]
if i have it sorted by create time descending, then switch to use last hour time range, the ordering i had is lost.  I'd prefer the ordering to remain sticky

**Comment by scale-tone** [comment]
Implemented in [v5.0](https://github.com/scale-tone/DurableFunctionsMonitor/releases/tag/v5.0). Please, validate.

**Comment by collinsbenjw** [comment]
Did a bit of testing and works great, thank you.
