### ISSUE TITLE
show time zone in column header?

### ISSUE THREAD

**Issue by drdamour** [scale-tone/DurableFunctionsMonitor#127]
could we show the timezone selected in the headers of timestamp columns?  i know it's not UTC cause it's not Z but it'd be nice to see it show eg

createdTime [MT]  or createdTime [GMT-0600]

**Comment by scale-tone** [comment]
Implemented in [v5.0](https://github.com/scale-tone/DurableFunctionsMonitor/releases/tag/v5.0). Please, validate.

**Comment by collinsbenjw** [comment]
Looks great, thank you.
