### ISSUE TITLE
type status selector UX suggestions

### ISSUE THREAD

**Issue by drdamour** [scale-tone/DurableFunctionsMonitor#128]
don't mean to hammer you, just been using it lately and have a suggestion/complaint I've found the type status selector to be a bit clunky.  The scroll makes it hard to find what i want and unclear what's currently selects (since selected things can be scrolled off).  the header telling me helps a little, but if i screen shot to share in email (which seems to be something i do quite a bit now...) the info can be lost.

something like select2's multi pillbox would keep the current selected visible and offer more of a search
https://select2.org/getting-started/basic-usage#multi-select-boxes-pillbox

i know probably not select2 cause jquery gets neg'd...but something like it.

**Comment by scale-tone** [comment]
Implemented in [v5.0](https://github.com/scale-tone/DurableFunctionsMonitor/releases/tag/v5.0). Please, validate.

**Comment by collinsbenjw** [comment]
Selector looks great, works as intended. Thank you.
