### ISSUE TITLE
allow multiple filters

### ISSUE THREAD

**Issue by drdamour** [scale-tone/DurableFunctionsMonitor#129]
if i could && multiple filters that would be really useful when looking into runs.  A suggested possible UX would be a list of filter badges/pillbox that could be removed or modified using the existing filtering dialog.

**Comment by scale-tone** [comment]
Hope to make it work in next release...

**Comment by scale-tone** [comment]
Closing this one in favor of https://github.com/microsoft/DurableFunctionsMonitor/issues/2
