### ISSUE TITLE
[Proposal] Support custom visualization templates for Orchestrations/Durable Entities

### ISSUE THREAD

**Issue by scale-tone** [scale-tone/DurableFunctionsMonitor#13]
Would be nice to quickly customize the Orchestration/Durable Entity details page, so that you can visualize your custom statuses in an app-specific way. E.g. display geo coordinates on a map.
We could have placeholders on the page, that are filled dynamically with HTML taken from files with predefined names.

That would allow to quickly build a custom administering portal/utility for your solution. 
Still important not to compromise safety.

**Comment by SamVanhoutte** [comment]
Curious how you see this.  Would you allow some kind of template that can take the actual state (as json) and visualize it in the way you want?  I like the idea, for sure !  This would allow our admin department to do better troubleshooting

**Comment by scale-tone** [comment]
> Would you allow some kind of template that can take the actual state (as json) and visualize it in the way you want?

Something like that indeed. But just need to find out the best solutions for the following:
1. What actual templating mechanism to use. Quick googling didn't produce any good candidates for JSON->HTML transformation, so I started thinking of maybe running [custom Razor templates on the backend side](https://anthonychu.ca/post/azure-functions-puppeteer-pdf-razor-template/) (ignore the PuppeteerSharp part there). Any better ideas?
2. Where to store the templates. Can think of just having a dedicated container with predefined name in the same Blob Storage. Once anything is there, DFM backend treats it as custom templates and renders them. Again, any better proposals?

**Comment by SamVanhoutte** [comment]
> What actual templating mechanism to use.

Honestly, as I'm a backend guy and don't have any front end / javascript experience, I think this will be hard for me to answer.  Is liquid templates a possibility, you think? 

> Where to store the templates

Agree that it would be great to store them together with the same storage account, as you'll need access to it, anyhow.  I guess you would think about a template per Entity type, right?

**Comment by scale-tone** [comment]
> Is liquid templates a possibility, you think?

Did you mean [Shopify's liquid](https://github.com/Shopify/liquid)? Not sure about that thing - it's in Ruby, so most likely hardly integratable with Functions...

>  I guess you would think about a template per Entity type, right?

Do you mean deriving a template file to be used from Orchestration/Entity's name:
![image](https://user-images.githubusercontent.com/5447190/97713019-8ce7a880-1abf-11eb-9ed4-fac021ce07ed.png)

?
Something like `ProcessAppointmentOrchestrator.template`, `SomeOtherOrchestrator.template` etc?

**Comment by SamVanhoutte** [comment]
Liquid templates is used in Logic Apps, for example:https://docs.microsoft.com/en-us/azure/logic-apps/logic-apps-enterprise-integration-liquid-transform
Probably also possible to generate html: https://medium.com/@ferryjongmans/json-transformation-with-liquid-e607be9094c0

Agree with the template, based on the name of the Orchestration or Entity

**Comment by scale-tone** [comment]
> Liquid templates

Cool, I can see there's a [.Net port of it](https://github.com/dotliquid/dotliquid), which looks promising. Will try it out...

**Comment by scale-tone** [comment]
Implemented in [v3.6](https://github.com/scale-tone/DurableFunctionsMonitor/releases/tag/v3.6)

**Comment by scale-tone** [comment]
@SamVanhoutte , can I please ask you to test and give some feedback? 

Note that it is [this .Net object](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.webjobs.extensions.durabletask.durableorchestrationstatus?view=azure-dotnet), that is being passed to your template, so property names are exactly like that (CamelCased). Also DotLiquid has some language flavour.

Thanks a lot!
