### ISSUE TITLE
Improvement: Allow search of event history 

### ISSUE THREAD

**Issue by junalmeida** [scale-tone/DurableFunctionsMonitor#135]
On instance page, on very large orchestrations, the page gets really slow and impossible to find specific information of what happened on the execution. I suggest to implement filters by time, type and names on the event history. 

![image](https://user-images.githubusercontent.com/991675/135104257-f8cd79af-8801-49e6-8e02-e536ce7fc81c.png)

**Comment by scale-tone** [comment]
Done in v5.1. Pls, validate.
