### ISSUE TITLE
Better documentation on full setup

### ISSUE THREAD

**Issue by aersamkull** [scale-tone/DurableFunctionsMonitor#138]
Hi there!

Thanks for this great tool that look great, too! 

I had some trouble setting everything up, even though it was not that tricky in the end. I think some small docu showing how to setup auth in Azure Portal for an Azure Function would be good for newbies. I did the following:

- Deploy to Azure Function obviously
- Added Auth in the portal but only Optional, not Required (is ok for me as I'm using VNet's)
- Then I had to add the redirect Uri to the App Registration

**Comment by scale-tone** [comment]
Documented authN/authZ setup in the new repo: https://github.com/microsoft/DurableFunctionsMonitor/wiki/How-to-configure-authentication.
If something else is missing, please, open a new issue there.
