### ISSUE TITLE
Not compatible with Azure Functions runtime version ~3

### ISSUE THREAD

**Issue by GuSuku** [scale-tone/DurableFunctionsMonitor#14]
When I deployed it to Azure Functions with runtime version (`FUNCTIONS_EXTENSION_VERSION`) as `~3`, it fails with following error:

```
Executing 'easyauth-config' (Reason='This function was programmatically called via the host APIs.', Id=*****)
Method not found: 'Void Microsoft.AspNetCore.Mvc.JsonResult..ctor(System.Object, Newtonsoft.Json.JsonSerializerSettings)'.
```

Got the same error even if I set `FUNCTIONS_V2_COMPATIBILITY_MODE` to `true` for the app.

The only fix was if I run it with `FUNCTIONS_EXTENSION_VERSION` to `~2`. 

Looks related to: https://github.com/HMoen/FunctionApp-JsonResult-Error

**Comment by scale-tone** [comment]
@GuSuku , thanks for reporting this, indeed DFM code is currently tied to runtime v2 (effectively, to .NET Core v2.1), so when deploying DFM to newly created Function App instances `FUNCTIONS_EXTENSION_VERSION` needs to be explicitly set to `~2`. The version of your Durable Functions project shouldn't matter though.

**Comment by scale-tone** [comment]
Fix looks surprisingly simple. @GuSuku, pls, validate.

**Comment by readnikhil** [comment]
Hi , Recently when I upgraded to use VS2019 and Core Tools version : 3.0.3 , I get this error when I have deploy the code to Azure portal using Azure pipelines. It gives this error Method not found: 'Void Microsoft.AspNetCore.Mvc.JsonResult..ctor(System.Object, Newtonsoft.Json.JsonSerializerSettings)' , irrespective of what function FUNCTIONS_EXTENSION_VERSION  I use .
I get the same error even if I use Azure function v2 or v3 and even when I redeploy old builds this error exists. Do you know what can be the issue . It had been working for me till I was using Vs2017 and core tools 2.*.* . I have now tried creating new function with v3 , vs2019 and also v2 with 2017 .But they all have same errors when I deploy using Azure pipelines. But when I publish them directly from Visual studio it works fine for me . Can someone please help ?

**Comment by scale-tone** [comment]
>  I get this error when I have deploy the code to Azure portal using Azure pipelines.

*Which* code exactly are you deploying, @readnikhil ?

**Comment by readnikhil** [comment]
Hi ,Thanks , I realized I should have asked this question in another post and not here . It is an error not related to this github codes but a custom code I developed. So I will create a new thread for my query.
