### ISSUE TITLE
'Function host is not running' when hosting the docker container in Azure Container Instances

### ISSUE THREAD

**Issue by nickraphael** [scale-tone/DurableFunctionsMonitor#18]
I'm trying to host in Azure Container Instances...

az container create --resource-group myGroup --name dfmonitor --ip-address Public --image scaletone/durablefunctionsmonitor:3.0 --os-type Linux

When I hit the public IP, I get 'Function host is not running.'

An idea what I'm doing wrong?

**Comment by scale-tone** [comment]
@nickraphael ,

The very first thing missing is the required environment variables - **AzureWebJobsStorage** and **DFM_HUB_NAME**. For ACI you typically specify them via **--environment-variables** argument.

But in general, DFM is not intended to be run in ACI. ACI doesn't support [EasyAuth module](https://docs.microsoft.com/en-us/azure/app-service/overview-authentication-authorization), while DFM relies on it to implement authN/authZ (without which your DFM endpoint will be left fully exposed to the public). So if you do wish to play with this combination, then please do that at your own risk.

The recommended way to run DFM in Azure is to deploy it to an Azure Function instance, [as described here](https://github.com/scale-tone/DurableFunctionsMonitor/tree/master/durablefunctionsmonitor.dotnetbackend#durablefunctionsmonitordotnetbackend). That will be also much cheaper than with ACI (even for free, if you don't exceed the free tier). It is also possible to deploy DFM _container_ to an Azure Function instance ([as documented here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-function-linux-custom-image?tabs=bash%2Cportal&pivots=programming-language-csharp)), but in that case it will be either _App Service_ or _Premium_ tier (Consumption mode is not supported by the platform yet) - so not as cheap as it could be.

**Comment by nickraphael** [comment]
Thanks so much!  Awsome reply.  Hope you're doing ok wherever you are.  FYI I'm currently planning a community talk about durable functions.  If you're ok, I'd like to include a section about monitoring using your solution.  That ok?  I'd be linking to your stuff directly.

**Comment by scale-tone** [comment]
> If you're ok, I'd like to include a section about monitoring using your solution. That ok? I'd be linking to your stuff directly.

Sure, I'm absolutely happy about that! Would even also be happy to take part in that activity (if not for current shitty circumstances...)
