### ISSUE TITLE
Getting error of Func.exe: 'func' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by gdodd1977** [scale-tone/DurableFunctionsMonitor#25]
After installing the app, I put in my storage account conn string. I then select the hub from the list that pops up. Once I do, it throws the error:

Func.exe: 'func' is not recognized as an internal or external command, operable program or batch file.

No other details are provided. My teammate is using the same exact conn string and hub and has no issues. I've uninstalled the extension and reinstalled a couple of times. I also verified I'm on the latest Azure Core Tools.

**Comment by scale-tone** [comment]
Hi @gdodd1977 ,
Are you sure you have Azure Core Tools installed **globally** (with npm's **-g** flag) on your machine?
What happens if you open a command prompt and type **func** in there?

**Comment by gdodd1977** [comment]
That did it! Thanks. I wasn't aware you needed the -g flag to install globally.
