### ISSUE TITLE
Login already in progress error

### ISSUE THREAD

**Issue by pksorensen** [scale-tone/DurableFunctionsMonitor#26]
I Deployed it to azure subscription and got the following when opening the app.

![image](https://user-images.githubusercontent.com/2718591/93689438-ceebfa80-face-11ea-871f-ede823f8392f.png)

**Comment by scale-tone** [comment]
This has nothing to do with DFM, but is a typical issue with AAD auth endpoint. You need to cleanup cookies (not only for your DFM URL, but also for login.microsoftonline.com) and re-login. In the meanwhile it should still work in porno-mode or in a different browser.
