### ISSUE TITLE
VsCode ext shows errors on MacOS with Homebrew

### ISSUE THREAD

**Issue by SamVanhoutte** [scale-tone/DurableFunctionsMonitor#27]
Hello 

Loving the promise of the tool, but it seems it does not work when using it locally on a MacOS.  When configuring everything in vs code (connection string + hub name), I get prompted with the following error message :  `Func.exe: /bin/sh: func: command not found` (func.exe is named differently on macos: `func`)

Is there a possibility to have this running on a macOs?

**Comment by scale-tone** [comment]
@SamVanhoutte , are you sure you have Azure Functions Core Tools installed **globally**, as explained in the [Prerequisites](https://github.com/scale-tone/DurableFunctionsMonitor#prerequisites)?

What happens when you type "func" in your command line?

**Comment by scale-tone** [comment]
With no response from @SamVanhoutte , assuming it resolved the problem and closing this. Please, reopen if anything is missing.

**Comment by SamVanhoutte** [comment]
Well, I have azure functions core tools locally indeed (installed through Rider and referenced in the Path).  So, when I execute `func` in the Terminal, I get the typical functions output, listing the help/arguments to start the functions host.  So func is found.

However, I tried to install it now through home brew: 
```
brew tap azure/functions
brew install azure-functions-core-tools@3
``` 

And that results in a new error message, but I obviously have the SDK installed of dotnet core:
`Func.exe: dotnet sdk is required for dotnet based functions. Please install https://microsoft.com/net`

Any idea how to resolve this? 

(I don't see how I can reopen this issue, btw)

**Comment by scale-tone** [comment]
@SamVanhoutte , normally DFM does work locally on MacOS. We need to figure out what went wrong in your specific case.

Do you have [Azure Functions extension for VsCode](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurefunctions) installed and are you capable of creating new Functions projects and debugging them locally?

**Comment by scale-tone** [comment]
@SamVanhoutte , did you have time to look deeper into this?
Does at least [Azure Functions extension for VsCode](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurefunctions) work?

btw. you could enable full logging of what commands DFM extension is trying to execute on your machine. For that open **~/. vscode/extensions/durablefunctionsmonitor.durablefunctionsmonitor-your-version/out/settings.json** file and set the *"logging"* field to **true**. Then restart VsCode, try to use the extension and then see what's inside  **~/. vscode/extensions/durablefunctionsmonitor.durablefunctionsmonitor-your-version/backend/backend-37072.log**

**Comment by SamVanhoutte** [comment]
I have just tested creating + running a new Azure function, locally in Vscode and that works.  
See this output:
```
> Executing task: func host start <

Azure Functions Core Tools (3.0.2931 Commit hash: d552c6741a37422684f0efab41d541ebad2b2bd2)
Function Runtime Version: 3.0.14492.0

Functions:

        OrchTest_HttpStart: [GET,POST] http://localhost:7071/api/OrchTest_HttpStart

        OrchTest_Hello: activityTrigger

        OrchTest: orchestrationTrigger

For detailed output, run func with --verbose flag.
Hosting environment: Production
Content root path: /Users/samvanhoutte/Temp/fxtest/bin/Debug/netcoreapp3.1
Now listening on: http://0.0.0.0:7071
Application started. Press Ctrl+C to shut down.
```

**Comment by SamVanhoutte** [comment]
after applying the logging, this is the content of the log file:
```
dotnet sdk is required for dotnet based functions. Please install https://microsoft.com/net
````
obviously, dotnet core is installed, (in terminal performing `dotnet new` just works)  and the output of `dotnet --version` is __3.1.402__

**Comment by SamVanhoutte** [comment]
`dotnet --list-sdks` result:

```
2.1.607 [/usr/local/share/dotnet/sdk]
3.1.101 [/usr/local/share/dotnet/sdk]
3.1.402 [/usr/local/share/dotnet/sdk]
```

**Comment by scale-tone** [comment]
@SamVanhoutte , there're no dotnet-based functions in DFM, as of today.

And so you're saying that when trying to open DFM in the same VsCode window you're still getting the 'command not found' error?
This is very strange, because [exactly the same command is being executed by it](https://github.com/scale-tone/DurableFunctionsMonitor/blob/master/durablefunctionsmonitor-vscodeext/src/BackendProcess.ts#L148), under (hopefully) the same context.

Can you please try to post the entire log-file? Also, what DFM version are you using?

**Comment by SamVanhoutte** [comment]
Yes, this is the error message now:

```
Func.exe: dotnet sdk is required for dotnet based functions. Please install https://microsoft.com/net
```

It might be related to a local installation (and context could be different), and I am using the docker container, so it's not very urgent for me, but still willing to help if you're after it

**Comment by scale-tone** [comment]
@SamVanhoutte , I would be very interested in figuring out the root cause of this, if you still have time to do more experiments.

What if you try to [install dotnet sdk via Homebrew](https://formulae.brew.sh/cask/dotnet-sdk) as well?

**Comment by SamVanhoutte** [comment]
That seems to be the trick to solve this, indeed.
The home brew install `brew cask install dotnet-sdk` did the trick

**Comment by scale-tone** [comment]
> The home brew install `brew cask install dotnet-sdk` did the trick

Great news! So, what we've learned from it is that whenever you're using Homebrew you'd better use Homebrew for everything. Is my understanding correct? :)

**Comment by scale-tone** [comment]
@SamVanhoutte , can we think of it as of resolved? Any more questions/comments/insights from your side?

**Comment by SamVanhoutte** [comment]
yes, for me, it's solved indeed.  thanks for your help and dedication
