### ISSUE TITLE
Manifest unknown when pulling docker image from docker hub

### ISSUE THREAD

**Issue by SamVanhoutte** [scale-tone/DurableFunctionsMonitor#28]
**Repro**
Execute `docker pull scaletone/durablefunctionsmonitor:latest`

**Error**
`Error response from daemon: manifest for scaletone/durablefunctionsmonitor:latest not found: manifest unknown: manifest unknown`

**Extra information**
Host system: MacOS

**Comment by scale-tone** [comment]
@SamVanhoutte , the tag "latest" doesn't exist among the [images](https://hub.docker.com/r/scaletone/durablefunctionsmonitor/tags) and is not going to exist.

Please, specify one of the existing tags, e.g. 
`docker pull scaletone/durablefunctionsmonitor:3.3
`

**Comment by SamVanhoutte** [comment]
thanks, that works.  I was confused by the command on docker hub.  thanks for the feedback!
