### ISSUE TITLE
[Proposal] Multiple Connection Strings when Deployed in Azure

### ISSUE THREAD

**Issue by javaadpatel** [scale-tone/DurableFunctionsMonitor#29]
Hi,

I really like this monitor, the detail is amazing. One enhancement that would be cool is the ability to swop between connection strings when its deployed in Azure. At the moment, we have multiple function apps we want to monitor so I've deployed multiple versions of the monitor, one for each, but it would be easier if I just had one monitor instance and then could swop between the connection strings.

I haven't looked at the code so I don't know how complex implementing something like would be, but I'd be happy to help if possible, unless you think its not viable right now.

**Comment by scale-tone** [comment]
Thanks for the great feedback, @javaadpatel !
As of the ability to switch between Task Hubs in Azure, this indeed would be a useful feature, and it was initially intended to be done like that. Unfortunately though, it's hardly possible when deployed to Azure - DFM is itself an Azure Functions instance, and (as of today) those instances are pretty much anchored to one particular Task Hub and cannot switch between them without external help. As a workaround, I could recommend just deploying multiple DFM instances (e.g. to the same App Service Plan aka to the same VM, to reduce costs), per each Task Hub.

Yet, switching between Task Hubs is absolutely possible with [VsCode extension](https://marketplace.visualstudio.com/items?itemName=DurableFunctionsMonitor.durablefunctionsmonitor), you can even stay connected to a multitude of them:
![image](https://user-images.githubusercontent.com/5447190/95067394-13e57300-0704-11eb-9f51-47d5cf11aabb.png)

To make that happen, the extension just spans out multiple local Functions instances on your devbox. Please, try it out if not yet.

**Comment by javaadpatel** [comment]
@scale-tone , what makes them anchored to one particular task hub? is it the setting in the azure portal, and could we maybe do something like keeping the setting instead in the already existing table storage account? 

That's a great suggestion, that's exactly what i'm planning to do, basically one main function app and then a dfm instance on each deployment slot to match my function app deployment slots.

I haven't checked out the VSCode extension but will do that now, thank you.

**Comment by scale-tone** [comment]
> what makes them anchored to one particular task hub?

It is exactly **AzureWebJobsStorage** and **DFM_HUB_NAME** [config settings](https://github.com/scale-tone/DurableFunctionsMonitor/blob/master/durablefunctionsmonitor.dotnetbackend/README.md#how-to-run), which you can always change via Azure Portal, Azure CLI or some sort of external script, but the Functions instance cannot change them by itself for itself (more precisely, it could theoretically change its DFM_HUB_NAME, but definitely not AzureWebJobsStorage). This is why the *Manage Storage Connection Settings* dialog is now so readonly, when running in Azure...

**Comment by javaadpatel** [comment]
Okay that now makes more sense to me, would it work if DFM was de-coupled from the storage account of the function app it was monitoring? That way DFM's storage can be in one account and then you'd pass in the value of the storage account you want to monitor

**Comment by scale-tone** [comment]
The account that you specify in DFM's **AzureWebJobsStorage** config setting - it should be *the same* account that your monitored Durable Functions are using. Otherwise the runtime won't be able to reach your orchestrations. That's exactly the problem - no way to "decouple" or dynamically configure the runtime.

**Comment by javaadpatel** [comment]
Okay, cool thank you for taking the time to explain that. I understand more now and will use the multiple slot approach 👍

**Comment by scale-tone** [comment]
Support for multiple Storage accounts implemented in [v5.0](https://github.com/scale-tone/DurableFunctionsMonitor/releases/tag/v5.0). Please, validate.
