### ISSUE TITLE
[Proposal] Persistable list of TaskHubs in VsCode ext

### ISSUE THREAD

**Issue by scale-tone** [scale-tone/DurableFunctionsMonitor#30]
At the moment it is possible to connect to multiple Task Hubs in VsCode ext (Azure Functions View Container -> DURABLE FUNCTIONS->small plug icon on the toolbar):
![image](https://user-images.githubusercontent.com/5447190/96588941-89486a80-12e4-11eb-8dd4-753d558e03ef.png)

Yet, this list is not persisted, so your connections are lost after VsCode restart.
Would be nice to:
* Persist that list of TaskHubs you're interested in, so it reappears there after restarting VsCode.
* Discuss whether it makes sense to store connection info along with that list. Need to find a **safe place** for it. Or maybe even better not to store it but obtain it on-the-fly out of your Azure credentials somehow...

**Comment by Arithmomaniac** [comment]
Re: credentials storage.. one common approach in VSCode seems to be to use node-keytar.
e.g. https://github.com/JetBrains/teamcity-vscode-extension/issues/11

**Comment by scale-tone** [comment]
Good news: by combining [Azure Account](https://marketplace.visualstudio.com/items?itemName=ms-vscode.azure-account) extension and [@azure/arm-storage](https://www.npmjs.com/package/@azure/arm-storage) package it appears to be possible to iterate through your storage accounts and even get their storage keys programmatically. Means that, once you're logged in into Azure in your VsCode, DFM ext will be able to show you all existing TaskHubs reachable by your account, and let you connect to them.
This should also eliminate the need for any secure storage.

So, will work on implementing this...

**Comment by Arithmomaniac** [comment]
Does that handle local/emulated storage as well?

**Comment by scale-tone** [comment]
> Does that handle local/emulated storage as well?

Nope :( And we must admit, support for exotic storages like that could be better. Forked this into a separate proposal #31 .

**Comment by scale-tone** [comment]
OK, all TaskHubs in your Azure subscription(s) can now be observed and connected to with [v3.4](https://marketplace.visualstudio.com/items?itemName=DurableFunctionsMonitor.durablefunctionsmonitor). Closing this, and please open more tickets if anything missing.
