### ISSUE TITLE
Func: 'func' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by ItFlyingStart** [scale-tone/DurableFunctionsMonitor#40]
Hi,

First of all: great initiative.

I try to make of Durable Functions Monitor, but I get the next error message. Do you know what could be the problem?

![image](https://user-images.githubusercontent.com/5562995/98231311-8d1ef280-1f5c-11eb-9eac-fc4d15495cca.png)

**Comment by scale-tone** [comment]
> First of all: great initiative.

Thanks! Just trying to be helpful :)

> Do you know what could be the problem?

Please, make sure Azure Functions Core Tools are installed **globally** (`npm i -g azure-functions-core-tools`), [as described in the Prerequisites](https://github.com/scale-tone/DurableFunctionsMonitor#prerequisites). The easiest way to check that is to type `func` in your command prompt/terminal.

And just for better understanding: do you have any Functions projects on your machine already? Are you able to run/debug them locally?

**Comment by ItFlyingStart** [comment]
Thanks for your answer.

I make use of MS Visual Studio 2017/2019 to develop Azure Durable Functions, and run/debug my solutions in Visual Studio. I thought that I don't need **install azure-functions-core-tools**, because it is already there (via Visual Studio extension/plugins).

I will try to install it globally.

**Comment by scale-tone** [comment]
@ItFlyingStart , let's hope that helped. Please, reopen, if anything else missing.
