### ISSUE TITLE
DFM seems too slow when inputs of orchestrations are large

### ISSUE THREAD

**Issue by SamVanhoutte** [scale-tone/DurableFunctionsMonitor#41]
Hello, 

In my current Azure Durable Functions project, I noticed DFM becomes often unresponsive and too slow.
I did not pinpoint the actual reason, but my guess would be that I have quite large documents as input to my orchestrations.

I have a batch synchronization proces, set up with the following sequence:

- HttpTrigger, triggers main process (asynchronous)
- Main process, calls 3rd party API, through sub orchestration
- For every node in the API response (iterate), a new Task is triggered that starts a new SubOrchestration.
- The input to that suborchestration is a json document (the node from that API) and can easily be around 100-300Kb

While I can try to reduce (remove some clutter) those documents, they will still be quite large.  And as the main layout include input+output in the view, this might result in that slow response.  

Some suggestions:

- I would prefer to be able to not "auto-query" when opening/starting the DFM view.  Now, there's always a query executed, that I might not need.  So, ideally I set my filters first and then press the query (refresh) button

- It would be great to have a flag that I can set so that the input/output are not visualized in the overview, as that would (probably) benefit scenarios like the one I have.

Looking forward to your insights

**Comment by scale-tone** [comment]
@SamVanhoutte, how about a long-awaited 'Cancel' button and an ability to choose the list of columns to be shown, as the first two steps to resolve this?

**Comment by SamVanhoutte** [comment]
cancel button : yes please (but still would be happy to avoid a query and set filters first, but no big deal if cancel button is there)

chose list of columns: would be great, as long as that also means the actual data fields will not be retrieved from the storage account or loaded in memory

**Comment by scale-tone** [comment]
> cancel button 
> chose list of column

Implemented this in [v3.7](https://github.com/scale-tone/DurableFunctionsMonitor/releases/tag/v3.7). Please, check.

**Comment by SamVanhoutte** [comment]
Forgot to update this one.  Thanks for the update, works better now!  Appreciated
