### ISSUE TITLE
Proper dark mode support in VSCode

### ISSUE THREAD

**Issue by calloncampbell** [scale-tone/DurableFunctionsMonitor#56]
Great tool but it would be nice if it could work in VS Code dark theme.

**Comment by scale-tone** [comment]
Thanks, @calloncampbell . In fact, I was waiting for this ticket right from vsCode extension's launch :)
Indeed, would be nice.

**Comment by junalmeida** [comment]
+1 
This is how it looks like for reference

![image](https://user-images.githubusercontent.com/991675/106934112-57b2ae00-66df-11eb-9984-6df09d235dab.png)

**Comment by scale-tone** [comment]
Yes, @junalmeida , it indeed looks embarrassing :(
Working on it...

**Comment by scale-tone** [comment]
Fixed in v4.1
