### ISSUE TITLE
[Poll] What do we do with two backend implementations?

### ISSUE THREAD

**Issue by scale-tone** [scale-tone/DurableFunctionsMonitor#6]
So, we now end up with two implementations of the backend part, both doing the same.

[The original one](https://github.com/scale-tone/DurableFunctionsMonitor/tree/master/durablefunctionsmonitor.functions) was written in TypeScript, and the rationale was to make it more democratic (easily adjustable to your own needs, whoever you are).

While working on the [VsCode extension](https://github.com/scale-tone/DurableFunctionsMonitor/tree/master/durablefunctionsmonitor-vscodeext), it turned out though, that C# is a better option (at least, for building the backend for that extension). The main reason is that I do want it (the backend HTTP endpoint) to be somehow protected, and it is only achievable when building it in C# (e.g. [the /runtime endpoint suppression proxy](https://github.com/scale-tone/DurableFunctionsMonitor/blob/master/durablefunctionsmonitor.dotnetbackend/proxies.json) can only do it's job in a C# project, while with TypeScript it would break the backend entirely, because the underlying framework relies on that endpoint).

So I had to [rewrite the backend in C#](https://github.com/scale-tone/DurableFunctionsMonitor/tree/master/durablefunctionsmonitor.dotnetbackend).

Now the question is: should we keep both implementations or can we get rid of TypeScript and proceed with C#?

I, of course, tend to the latter option, because:
* Obviously, maintaining both would be twice as more difficult.
* C# works faster (doesn't make HTTP calls to itself).
* C# Durable Functions API exposes more functionality (APIs for other languages are lagging behind).
* I'm personally way more comfortable with C# than with TypeScript :)

But I'm totally open for suggestions. So any thoughts?

**Comment by alberto-riggi** [comment]
I agree with you (abandoning ts), sharing at least your reasons 1,2 and 4. 
Haven't worked with ts durable function api, so I can't tell about point 3.

Regards

**Comment by scale-tone** [comment]
Cool, then **durablefunctionsmonitor.functions** is now officially declared to be deprecated :)
