### ISSUE TITLE
Opening Instance on orchestration with lot of activities timeout

### ISSUE THREAD

**Issue by bhugot** [scale-tone/DurableFunctionsMonitor#64]
Hello,

I can't open orchestration instance with 10k activities in it. The page in vs code timeout after 10 second and display doesn't say anything just loading bar is freeze.

Regards.

**Comment by scale-tone** [comment]
Hi @bhugot , I believe, that page doesn't 'timeout after 10 second', but simply takes a lot of time to render. In my experiments it takes roughly 1 minute per every 1K events, so if you just wait a little longer... you might eventually be able to see your 10K activities.

That said, I do agree, that it would make sense to add some infinite scrolling logic to this details page as well.

But I'm also very curious to know how you managed to run an orchestration with _so many activities_ in it. Didn't know that it's even possible and certainly it's not recommended (the orchestration would take too long to be replayed). 
Is it a real-life scenario or you're just doing a stress test?

**Comment by bhugot** [comment]
Hello it s Real life execution it s parallele activities. Rewind work really well  and is fast. It s some long proccess that de run this way.

**Comment by scale-tone** [comment]
Thanks for reporting this. Somewhat fixed in v4.2: the page now initially renders first 200 events and then can render more, as you scroll down. Please, validate.

**Comment by bhugot** [comment]
Thanks it s really better.
