### ISSUE TITLE
Support many/path/segments

### ISSUE THREAD

**Issue by drdamour** [scale-tone/DurableFunctionsMonitor#66]
I tried to put my stuff in this/path but it fails because the static assets won't load.

`<DurableFunctionsMonitorRoutePrefix>this/path</DurableFunctionsMonitorRoutePrefix>`

**Comment by scale-tone** [comment]
Didn't get this one, sorry.
Can you please elaborate on your setup, what you're trying to achieve and what errors you're getting?

**Comment by drdamour** [comment]
forgot to code quote the xml, check now

**Comment by scale-tone** [comment]
In that case it is indeed a bug. Thanks for reporting!

**Comment by scale-tone** [comment]
Fixed in v4.3. Please, validate.
