### ISSUE TITLE
Use server-directed login flow when possible

### ISSUE THREAD

**Issue by drdamour** [scale-tone/DurableFunctionsMonitor#69]
i was kinda surprised even though my app had already setup easyauth with the .auth/login/aad/callback reply url i had to go so far as to add the dfmon path too.  I'm guessing it's because ecmascript needs tokens via implict flow maybe?  probably because you have it setup to work in so many different ways like vs code extension)

 it'd be nice if it could just work as is with my existing auth configurations since the backend principal is already filled

 i'm imaging such a setup has the backend generating function providing the necessary token information to the frontend by script laid within the dom passed to the app init, least that's how i've done things like tha tin the past, falling back to existinig auth flow

**Comment by scale-tone** [comment]
Not sure it is possible. AAD requires exact match for that reply URL (at least, as of today), and the URL needs to point to DfMon's endpoint (otherwise it won't get the token). Need to do more experiments to be sure...

But can you please describe your setup? Are you using [server-directed login flow](https://github.com/cgillum/easyauth/wiki/Login#server-directed-login) or client library (msal, I presume)? What was the error message you got from AAD?

**Comment by drdamour** [comment]
yeah but it's your tool sending the final reply back path...it's just when i access ti at `path/` it asks to redirect to `path/` and if i access it at `path` it asks to come back to `path`.    generally you return to a single entry point with then redirects you to the final place

here's it's working
![image](https://user-images.githubusercontent.com/1514496/111000437-4b092180-833f-11eb-876e-e7dbd7880eeb.png)


here's it' failing
![image](https://user-images.githubusercontent.com/1514496/111000470-58bea700-833f-11eb-8b3f-02abd51239da.png)


it just your standard reply url isn't kosher error
![image](https://user-images.githubusercontent.com/1514496/111000661-b4893000-833f-11eb-8400-6fefd7bd24ce.png)

i noticed that when it a request to `path/instance` it replies back at just `path` so i figured settling on `path` woudl be good
![image](https://user-images.githubusercontent.com/1514496/111000767-e1d5de00-833f-11eb-860a-1d46ef04d0ca.png)

**Comment by drdamour** [comment]
original comment on wrong issue.


it's def possible, i've done it a few times.  your client i think is assuming there's no claims established so it's using MSAL maybe to grab one?

yes server direct login flow, so the claims have been established and are available to the backend.  so you just have to pass what you need to the  frontend..which generally is just a flat to not do the msal token grab because auth is established already.  it's only for the case of embedding the tool in an existing func app though

**Comment by scale-tone** [comment]
So it's then rather about supporting server-directed flow (which is definitely better, faster and much less troublesome), correct?
That looks absolutely possible (when run in Azure).

**Comment by drdamour** [comment]
yeah i think that would eliminate the need for the extra reply urls

**Comment by scale-tone** [comment]
Note to myself: in server-directed flow user name is being passed via `http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name` claim (unlike `preferred_username` with client-directed).
No idea why...

**Comment by drdamour** [comment]
in my setup i'm still getting name and preferred_username claims and NOT http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name

i do have a claim for http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress

i'm no expert at this stuff...i think the list of claims is controlled by the tenant perhaps?

**Comment by drdamour** [comment]
ok looking closer it appears the claims i'm talking about come from the https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens , and i think that should be enough for an easy auth for what DFMon requires and name and preferred_username are both present there because i'm using v2.  note about preferred_username


preferred_username | String | The primary username that represents the user. It could be an email address, phone number, or a generic username without a specified format. Its value is mutable and might change over time. Since it is mutable, this value must not be used to make authorization decisions. It can be used for username hints, however, and in human-readable UI as a username. The profile scope is required in order to receive this claim. **Present only in v2.0 tokens.**

i think no matter what...since you can't know who is providing the access token you probably need to make it an overideable config setting

**Comment by scale-tone** [comment]
Fixed in v4.3. Please, validate.
