### ISSUE TITLE
trailing / causes AAD auth errors

### ISSUE THREAD

**Issue by drdamour** [scale-tone/DurableFunctionsMonitor#70]
we noticed that a trailing / causes auth errors because redirect doesn't match allowed list

IE https://www.example.com/dfmon vs https://www.example.com/dfmon/ i think the former should be preferred, but it should be normalized.

somewhat related to #69

**Comment by scale-tone** [comment]
Can't repro this one...

Those URLs you mentioned - is it what you were specifying in the list of Redirect URIs on your AAD app registration page?

**Comment by drdamour** [comment]
yeah but it's your tool sending the final reply back path...it's just when i access ti at `path/` it asks to redirect to `path/` and if i access it at `path` it asks to come back to `path`.    generally you return to a single entry point with then redirects you to the final place

here's it's working
![image](https://user-images.githubusercontent.com/1514496/111000437-4b092180-833f-11eb-876e-e7dbd7880eeb.png)


here's it' failing
![image](https://user-images.githubusercontent.com/1514496/111000470-58bea700-833f-11eb-8b3f-02abd51239da.png)


it just your standard reply url isn't kosher error
![image](https://user-images.githubusercontent.com/1514496/111000661-b4893000-833f-11eb-8400-6fefd7bd24ce.png)

i noticed that when it a request to `path/instance` it replies back at just `path` so i figured settling on `path` woudl be good
![image](https://user-images.githubusercontent.com/1514496/111000767-e1d5de00-833f-11eb-860a-1d46ef04d0ca.png)

**Comment by scale-tone** [comment]
OK, so as I understood it, it's some specificity around trailing slash, that becomes visible when `DurableFunctionsMonitorRoutePrefix` is being set. Will investigate...

**Comment by scale-tone** [comment]
Fixed in v4.3. Please, validate.
