### ISSUE TITLE
UI needs local time settings

### ISSUE THREAD

**Issue by drdamour** [scale-tone/DurableFunctionsMonitor#71]
would be really nice to have a local time setting in the UX

**Comment by scale-tone** [comment]
Would a config setting be acceptable instead? 
Trying to keep the UI at its minimum...

**Comment by drdamour** [comment]
yeah mostly, but it'd really be nice to flip between em.  have u seen how app insights does it? i like that experience personally.  we do have some diff timezone people on staff.

**Comment by scale-tone** [comment]
Makes sense then

**Comment by scale-tone** [comment]
Fixed in v4.5. Please, validate.

**Comment by drdamour** [comment]
this works great, do have a slight suggestion in #127 thx for implementing
