### ISSUE TITLE
UI deep links with applied filters sorting

### ISSUE THREAD

**Issue by drdamour** [scale-tone/DurableFunctionsMonitor#72]
it'd be really nice as you apply changes to the dash/list with the timespan and any filtering that the href of the browser was updated to reflect that state so you could share with colleagues

**Comment by scale-tone** [comment]
Would be nice to have indeed. The only reason deep links are not there yet is because it wouldn't make any sense for VsCode ext. But for standalone/injected mode it's really helpful.

**Comment by scale-tone** [comment]
Fixed in v4.3. Please, validate.
