### ISSUE TITLE
Last X quick timer filters

### ISSUE THREAD

**Issue by drdamour** [scale-tone/DurableFunctionsMonitor#73]
the date time picker is really nice, but most the time i just wanna see the last X minutes, hours, days, weeks...be nice to add some quick pick list for those right around here.
![image](https://user-images.githubusercontent.com/1514496/110994564-2bb9c680-8336-11eb-8f1f-9ed3e2002f62.png)

**Comment by scale-tone** [comment]
Would be nice to have indeed

**Comment by scale-tone** [comment]
Fixed in v4.3. Please, validate.
