### ISSUE TITLE
Consider Scheduled Maintenance Cleanups?

### ISSUE THREAD

**Issue by drdamour** [scale-tone/DurableFunctionsMonitor#78]
we're gonna be adding some maintenance cleanup routines to clear out entities and orchestrations over X days old in the set of Y states...on a schedule.  You have very similar functionality, just not on a schedule.  

I was thinking if we leveraged the Disable attribute could add them to this util and then they could be opt in enabled based on host.json settings of some sort.  

this could just as easily be it's own thing, but starting a new project vs contributing to existing has different approval process at my company.

Are you open to such a contribution?

**Comment by scale-tone** [comment]
So you would want DfMon to periodically do those cleanups in the background? If yes, then I'm afraid it is way out of scope for a monitoring tool like this one.
Plus, those things are easily automatable with e.g. [Functions Core Tools](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-instance-management?tabs=csharp#azure-functions-core-tools-7). Or else you could just have a timer-triggered Function, inject DurableClient in it and call its PurgeXXXHistory() methods.

**Comment by drdamour** [comment]
Yea thats how i implemented it.  But have dozens of DF based function apps and tired of copy pasta.  Not much different than a rolling log appender really.  Understand u think its beyond the scope of your project.
