### ISSUE TITLE
The From Filter does not work for values after 12pm

### ISSUE THREAD

**Issue by shelbaz** [scale-tone/DurableFunctionsMonitor#9]
When trying to filter by date using the "From" top left filter, it seems to not be taking the PM into account for converting the time to 24hr format that it is stored in the table. 

![image](https://user-images.githubusercontent.com/18130581/69891272-53178c00-12c9-11ea-987e-675922330377.png)

**Comment by scale-tone** [comment]
Hi @shelbaz , thanks for reporting this, but can you please provide a better screenshot demonstrating the problem? From your screenshot it looks like it is working properly - only orchestrations **after 2019-11-29T17:05** are shown...

**Comment by scale-tone** [comment]
Just tried this on a machine with US locale, don't see that happening:
![image](https://user-images.githubusercontent.com/5447190/70073359-00a3db80-15f9-11ea-9de9-1d3fb5c02aec.png)

Although I do admit the default material-ui's DateTimePicker is a mess. Probably, we need to choose something better...

Closing this so far. Please, reopen if you have more repro.
