### ISSUE TITLE
Enhancement to monitor multiple storage accounts

### ISSUE THREAD

**Issue by mec-sa** [scale-tone/DurableFunctionsMonitor#95]
For us we have 2 azure function code bases, one for nodejs and another for .netcore.
For each of the code base we deploy them to two environments, staging and production. So we ended up with 4 environments in total. Right now to get the full DFM benefits we would have deploy the code to 4 resources.
It would so much easier if DFM allows for store multiple storage connection strings, and we can easily switch between the environment to monitor from some UI dropdown.

Most people probably don't have multiple durable function code bases, but it's definitely a common practice to have multiple environments.

**Comment by scale-tone** [comment]
Managing multiple storage accounts with single DfMon instance would indeed be a great thing to have. But sadly it isn't technically possible, at least as of today. DfMon is itself an Azure Durable Function, and Durable Functions do not support working with multiple storage accounts.

The alternatives for you could be:
1. Put your Task Hubs into the same storage account. Then all of them would be observable by a single DfMon instance.
2. Use DfMon in 'injected' mode, aka make it a part of your .Net Core project. See instructions in the [NuGet package readme](https://www.nuget.org/packages/DurableFunctionsMonitor.DotNetBackend).
3. Or just use DfMon as [VsCode extension](https://marketplace.visualstudio.com/items?itemName=DurableFunctionsMonitor.durablefunctionsmonitor). There all your storage accounts and Task Hubs in them will become visible at once.

**Comment by scale-tone** [comment]
Support for multiple Storage accounts implemented in [v5.0](https://github.com/scale-tone/DurableFunctionsMonitor/releases/tag/v5.0). Please, validate.
