### ISSUE TITLE
Gantt chart in VS Code isn't showing activity visualizations for simple sequence

### ISSUE THREAD

**Issue by cgillum** [scale-tone/DurableFunctionsMonitor#96]
Repro steps:

1. Install VS Code extension (I installed it today)
2. Connect it to my local storage emulator
3. Run a "Hello Sequence" orchestration from the samples

The resulting Gantt chart doesn't show visuals for the three activity functions that were run. The text is there showing the name of the functions and their execution time, but no colorful horizontal bars.

![image](https://user-images.githubusercontent.com/2704139/121737282-81287f80-caad-11eb-9b84-14d1cad764d5.png)

I was expecting to see bars for each of the activity function executions, just like the screenshot in the README for this project. I'll understand if this is because the activity functions completed so quickly, but it would be nice to have a small graphic showing approximately where it started and completed.

(BTW, this is an awesome tool - I would love to start promoting it more - thanks for the hard work you put into it)

**Comment by scale-tone** [comment]
Really appreciate your feedback, @cgillum ! I've seen you mentioned DfMon in the official docs, thanks a lot for that!
Now people have finally started using it, which is plain to see from the number of issues raised :)

Back to business, I'm afraid, we're hitting [mermaid](https://github.com/mermaid-js/mermaid)'s limitation here, which is incapable of showing intervals smaller than 1 sec (after all it was originally intended for project management, where everything is  measured in human-hours, not human-milliseconds).
But I can try to find some workaround...

**Comment by scale-tone** [comment]
fixed in v4.6. Pls, validate.
